server:
  port: 8000

# database connections  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_app_prod
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root@123}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
    show-sql: false

# Security Configuration
security:
  jwt:
    secret: ${JWT_SECRET:mySecretKeyForJWTTokenGenerationThatIsAtLeast64CharactersLongToMeetHMACRequirements}
    access-ttl-seconds: 3600
    refresh-ttl-seconds: 86400
    issuer: auth-app-backend